// <auto-generated />
namespace WebSrv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update20180301v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update20180301v1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803011746267_Update-2018-03-01-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
